import os
import fnmatch
from typing import Optional
from docker_slim.layer_analyzer import LayerAnalysis
from docker_slim.pattern_detector import PatternDetector, PatternIssue
from docker_slim.utils import KNOWN_CACHE_PATTERNS, normalize_path, format_size


class Optimizer:
    def __init__(self, analysis: LayerAnalysis, exclude_patterns: Optional[list] = None):
        self.analysis = analysis
        self.exclude_patterns = exclude_patterns or []
        self.pattern_detector = PatternDetector(analysis)

    def generate_cleanup_commands(self) -> list:
        commands = []
        commands.append("# === Docker Slim Auto-generated Cleanup Commands ===")
        commands.append("")

        commands.append("# --- Remove package manager caches ---")
        cache_cleanup = {
            "/var/cache/apt": "rm -rf /var/cache/apt/* /var/lib/apt/lists/*",
            "/var/cache/yum": "rm -rf /var/cache/yum/*",
            "/var/cache/dnf": "rm -rf /var/cache/dnf/*",
            "/var/cache/pacman": "rm -rf /var/cache/pacman/pkg/*",
            "/var/cache/apk": "rm -rf /var/cache/apk/*",
            "/root/.cache": "rm -rf /root/.cache/*",
            "/tmp": "rm -rf /tmp/*",
            "/var/tmp": "rm -rf /var/tmp/*",
            "/var/log": "find /var/log -type f -name '*.log' -delete",
            "/usr/share/doc": "rm -rf /usr/share/doc/*",
            "/usr/share/man": "rm -rf /usr/share/man/*",
            "/usr/share/info": "rm -rf /usr/share/info/*",
        }
        for path, cmd in cache_cleanup.items():
            commands.append(f"RUN {cmd}")

        commands.append("")
        commands.append("# --- Remove Python bytecode ---")
        commands.append("RUN find / -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true")
        commands.append("RUN find / -type f -name '*.pyc' -delete 2>/dev/null || true")
        commands.append("RUN find / -type f -name '*.pyo' -delete 2>/dev/null || true")

        commands.append("")
        commands.append("# --- Remove static libraries and headers ---")
        commands.append("RUN find / -type f -name '*.a' -delete 2>/dev/null || true")
        commands.append("RUN find / -type f -name '*.la' -delete 2>/dev/null || true")

        commands.append("")
        commands.append("# --- Remove documentation ---")
        commands.append(r"RUN find / -type f \( -name 'README*' -o -name 'CHANGELOG*' -o -name 'LICENSE*' -o -name 'COPYING*' \) -delete 2>/dev/null || true")

        return commands

    def generate_optimized_dockerfile(self, base_image: str, extra_commands: Optional[list] = None) -> str:
        lines = []
        lines.append(f"# === Docker Slim Optimized Dockerfile ===")
        lines.append(f"# Base image: {base_image}")
        lines.append(f"# Generated by docker-slim v1.0.0")
        lines.append("")

        parts = base_image.split(":")
        if len(parts) == 2:
            image, tag = parts
        else:
            image = parts[0]
            tag = "latest"

        lines.append(f"FROM {image}:{tag}")
        lines.append("")

        lines.append("# --- Slimming: Remove package manager caches ---")
        lines.append("RUN rm -rf /var/cache/apt/* /var/lib/apt/lists/* \\")
        lines.append("    && rm -rf /var/cache/yum/* \\")
        lines.append("    && rm -rf /var/cache/dnf/* \\")
        lines.append("    && rm -rf /var/cache/apk/* \\")
        lines.append("    && rm -rf /root/.cache/* \\")
        lines.append("    && rm -rf /tmp/* /var/tmp/*")

        lines.append("")
        lines.append("# --- Slimming: Remove Python cache ---")
        lines.append("RUN find / -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true \\")
        lines.append("    && find / -type f -name '*.pyc' -delete 2>/dev/null || true \\")
        lines.append("    && find / -type f -name '*.pyo' -delete 2>/dev/null || true")

        lines.append("")
        lines.append("# --- Slimming: Remove docs and man pages ---")
        lines.append("RUN rm -rf /usr/share/doc/* \\")
        lines.append("    && rm -rf /usr/share/man/* \\")
        lines.append("    && rm -rf /usr/share/info/* \\")
        lines.append("    && rm -rf /usr/share/locale/*")

        lines.append("")
        lines.append("# --- Slimming: Remove static libs ---")
        lines.append("RUN find / -type f -name '*.a' -delete 2>/dev/null || true \\")
        lines.append("    && find / -type f -name '*.la' -delete 2>/dev/null || true")

        if extra_commands:
            lines.append("")
            lines.append("# --- Custom commands ---")
            for cmd in extra_commands:
                lines.append(cmd)

        return "\n".join(lines)

    def estimate_savings(self) -> dict:
        issues = self.pattern_detector.detect_all()
        total_estimated_savings = 0
        by_category = {}

        for issue in issues:
            total_estimated_savings += issue.size_estimate
            cat = issue.pattern_type
            if cat not in by_category:
                by_category[cat] = 0
            by_category[cat] += issue.size_estimate

        current_size = self.analysis.total_size
        estimated_new_size = max(0, current_size - total_estimated_savings)
        savings_percent = (total_estimated_savings / current_size * 100) if current_size > 0 else 0

        return {
            "current_size": current_size,
            "estimated_savings": total_estimated_savings,
            "estimated_new_size": estimated_new_size,
            "savings_percent": savings_percent,
            "by_category": by_category,
        }