import os
import fnmatch
from typing import Optional
from docker_slim.layer_analyzer import LayerAnalysis
from docker_slim.pattern_detector import PatternDetector, PatternIssue
from docker_slim.utils import KNOWN_CACHE_PATTERNS, normalize_path, format_size, matches_any_glob


class Optimizer:
    def __init__(self, analysis: LayerAnalysis, exclude_patterns: Optional[list] = None):
        self.analysis = analysis
        self.exclude_patterns = exclude_patterns or []
        self.pattern_detector = PatternDetector(analysis)

    def build_detected_cache_targets(self) -> list:
        issues = self.pattern_detector.detect_all()
        targets = set()
        for issue in issues:
            if issue.pattern_type == "package_cache":
                for detail in issue.details:
                    if isinstance(detail, tuple) and len(detail) >= 1:
                        p = normalize_path(detail[0])
                        parent = os.path.dirname(p)
                        if parent:
                            targets.add("/" + parent)
        return sorted(targets)

    def generate_cleanup_commands(self) -> list:
        commands = []
        commands.append("# === Docker Slim Auto-generated Cleanup Commands ===")
        commands.append("")

        commands.append("# --- Remove package manager caches ---")
        cache_cleanup = {
            "/var/cache/apt": "rm -rf /var/cache/apt/* /var/lib/apt/lists/*",
            "/var/cache/yum": "rm -rf /var/cache/yum/*",
            "/var/cache/dnf": "rm -rf /var/cache/dnf/*",
            "/var/cache/pacman": "rm -rf /var/cache/pacman/pkg/*",
            "/var/cache/apk": "rm -rf /var/cache/apk/*",
            "/root/.cache": "rm -rf /root/.cache/*",
            "/tmp": "rm -rf /tmp/*",
            "/var/tmp": "rm -rf /var/tmp/*",
            "/var/log": "find /var/log -type f -name '*.log' -delete",
            "/usr/share/doc": "rm -rf /usr/share/doc/*",
            "/usr/share/man": "rm -rf /usr/share/man/*",
            "/usr/share/info": "rm -rf /usr/share/info/*",
        }
        for path, cmd in cache_cleanup.items():
            commands.append(f"RUN {cmd}")

        commands.append("")
        commands.append("# --- Remove Python bytecode ---")
        commands.append("RUN find / -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true")
        commands.append("RUN find / -type f -name '*.pyc' -delete 2>/dev/null || true")
        commands.append("RUN find / -type f -name '*.pyo' -delete 2>/dev/null || true")

        commands.append("")
        commands.append("# --- Remove npm/yarn cache ---")
        commands.append("RUN find / -type d -name '.npm' -exec rm -rf {} + 2>/dev/null || true")
        commands.append(r"RUN find / -type d \( -name '.cache' -path '*/node_modules/.cache' \) -exec rm -rf {} + 2>/dev/null || true")

        commands.append("")
        commands.append("# --- Remove static libraries and headers ---")
        commands.append("RUN find / -type f -name '*.a' -delete 2>/dev/null || true")
        commands.append("RUN find / -type f -name '*.la' -delete 2>/dev/null || true")

        commands.append("")
        commands.append("# --- Remove documentation ---")
        commands.append(r"RUN find / -type f \( -name 'README*' -o -name 'CHANGELOG*' -o -name 'LICENSE*' -o -name 'COPYING*' \) -delete 2>/dev/null || true")

        return commands

    def generate_optimized_dockerfile(self, base_image: str, extra_commands: Optional[list] = None) -> str:
        lines = []
        lines.append(f"# === Docker Slim Optimized Dockerfile ===")
        lines.append(f"# Base image: {base_image}")
        lines.append(f"# Generated by docker-slim")
        lines.append("")

        parts = base_image.split(":")
        if len(parts) == 2:
            image, tag = parts
        else:
            image = parts[0]
            tag = "latest"

        lines.append(f"FROM {image}:{tag}")
        lines.append("")

        lines.append("# --- Slimming: Remove package manager caches ---")
        lines.append("RUN rm -rf /var/cache/apt/* /var/lib/apt/lists/* \\")
        lines.append("    && rm -rf /var/cache/yum/* \\")
        lines.append("    && rm -rf /var/cache/dnf/* \\")
        lines.append("    && rm -rf /var/cache/apk/* \\")
        lines.append("    && rm -rf /root/.cache/pip \\")
        lines.append("    && rm -rf /root/.npm \\")
        lines.append("    && rm -rf /root/.cache/yarn \\")
        lines.append("    && rm -rf /root/.cache/* \\")
        lines.append("    && rm -rf /tmp/* /var/tmp/*")

        lines.append("")
        lines.append("# --- Slimming: Remove Python cache ---")
        lines.append("RUN find / -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true \\")
        lines.append("    && find / -type f -name '*.pyc' -delete 2>/dev/null || true \\")
        lines.append("    && find / -type f -name '*.pyo' -delete 2>/dev/null || true")

        lines.append("")
        lines.append("# --- Slimming: Remove docs and man pages ---")
        lines.append("RUN rm -rf /usr/share/doc/* \\")
        lines.append("    && rm -rf /usr/share/man/* \\")
        lines.append("    && rm -rf /usr/share/info/* \\")
        lines.append("    && rm -rf /usr/share/locale/*")

        lines.append("")
        lines.append("# --- Slimming: Remove static libs ---")
        lines.append("RUN find / -type f -name '*.a' -delete 2>/dev/null || true \\")
        lines.append("    && find / -type f -name '*.la' -delete 2>/dev/null || true")

        if extra_commands:
            lines.append("")
            lines.append("# --- Custom commands ---")
            for cmd in extra_commands:
                lines.append(cmd)

        return "\n".join(lines)

    def generate_export_slim_script(self, image_name: str, output_dockerfile: str = "Dockerfile.slim", output_tag: str = "") -> str:
        if not output_tag:
            output_tag = image_name.split(":")[0] + ":slim" if ":" in image_name else image_name + ":slim"

        script = []
        script.append("#!/usr/bin/env bash")
        script.append("# ==============================================================")
        script.append("# Docker Slim - Full Export & Rebuild Pipeline")
        script.append("# ==============================================================")
        script.append(f"# Source image:  {image_name}")
        script.append(f"# Output image:  {output_tag}")
        script.append(f"# Dockerfile:    {output_dockerfile}")
        script.append("")
        script.append("set -euo pipefail")
        script.append("")

        script.append("# ------------------------------------------------------------")
        script.append("# Stage 1: Export filesystem from the original image")
        script.append("# ------------------------------------------------------------")
        script.append("echo '[Stage 1/4] Exporting filesystem from source image...'")
        script.append("CONTAINER_ID=$(docker create " + image_name + ")")
        script.append("EXPORT_DIR=$(mktemp -d)")
        script.append(r'docker export "$CONTAINER_ID" | tar -xC "$EXPORT_DIR"')
        script.append(r'docker rm "$CONTAINER_ID" > /dev/null')
        script.append("echo '  Filesystem exported to: ' $EXPORT_DIR")
        script.append("")

        script.append("# ------------------------------------------------------------")
        script.append("# Stage 2: Clean up caches and unnecessary files")
        script.append("# ------------------------------------------------------------")
        script.append("echo '[Stage 2/4] Cleaning up caches and unnecessary files...'")
        script.append(r'BEFORE_SIZE=$(du -sb "$EXPORT_DIR" | cut -f1)')

        script.append(r'rm -rf "$EXPORT_DIR/var/cache/apt"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/var/lib/apt/lists"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/var/cache/yum"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/var/cache/dnf"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/var/cache/apk"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/root/.cache"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/root/.pip/cache" 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/root/.npm" 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/root/.cache/yarn" 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/root/.cache/pip" 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/tmp"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/var/tmp"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/usr/share/doc"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/usr/share/man"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/usr/share/info"/* 2>/dev/null || true')
        script.append(r'rm -rf "$EXPORT_DIR/usr/share/locale"/* 2>/dev/null || true')
        script.append(r'find "$EXPORT_DIR" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true')
        script.append(r'find "$EXPORT_DIR" -type f -name "*.pyc" -delete 2>/dev/null || true')
        script.append(r'find "$EXPORT_DIR" -type f -name "*.a" -delete 2>/dev/null || true')
        script.append(r'find "$EXPORT_DIR" -type f -name "*.la" -delete 2>/dev/null || true')
        script.append(r'find "$EXPORT_DIR" -type d -name ".npm" -exec rm -rf {} + 2>/dev/null || true')
        script.append(r'find "$EXPORT_DIR" -type f \( -name "README*" -o -name "CHANGELOG*" -o -name "LICENSE*" \) -delete 2>/dev/null || true')
        script.append("")
        script.append(r'AFTER_SIZE=$(du -sb "$EXPORT_DIR" | cut -f1)')
        script.append(r'SAVED=$((BEFORE_SIZE - AFTER_SIZE))')
        script.append(r'echo "  Before cleanup: " $(numfmt --to=iec $BEFORE_SIZE 2>/dev/null || echo ${BEFORE_SIZE})')
        script.append(r'echo "  After cleanup:  " $(numfmt --to=iec $AFTER_SIZE 2>/dev/null || echo ${AFTER_SIZE})')
        script.append(r'echo "  Saved:          " $(numfmt --to=iec $SAVED 2>/dev/null || echo ${SAVED})')
        script.append("")

        script.append("# ------------------------------------------------------------")
        script.append("# Stage 3: Generate Dockerfile from cleaned filesystem")
        script.append("# ------------------------------------------------------------")
        script.append("echo '[Stage 3/4] Generating Dockerfile...'")
        script.append("cat > " + output_dockerfile + " << 'DOCKERFILE_EOF'")
        script.append(f"FROM scratch")
        script.append(f"COPY . /")
        script.append(f'CMD ["/bin/sh"]')
        script.append("DOCKERFILE_EOF")
        script.append(f"cp -r \"$EXPORT_DIR/.\" . 2>/dev/null || true")
        script.append("echo '  Dockerfile written to: " + output_dockerfile + "'")
        script.append("")

        script.append("# ------------------------------------------------------------")
        script.append("# Stage 4: Build the slimmed image")
        script.append("# ------------------------------------------------------------")
        script.append(f"echo '[Stage 4/4] Building slimmed image: {output_tag} ...'")
        script.append(f"docker build -f {output_dockerfile} -t {output_tag} .")
        script.append("")
        script.append("echo ''")
        script.append("echo '=============================================================='")
        script.append("echo '  Slimmed image built successfully!'")
        script.append(f"echo '  Image: {output_tag}'")
        script.append("echo '=============================================================='")
        script.append("docker images " + output_tag)
        script.append("")

        return "\n".join(script)

    def estimate_savings(self) -> dict:
        issues = self.pattern_detector.detect_all()
        total_estimated_savings = 0
        by_category = {}

        for issue in issues:
            total_estimated_savings += issue.size_estimate
            cat = issue.pattern_type
            if cat not in by_category:
                by_category[cat] = 0
            by_category[cat] += issue.size_estimate

        current_size = self.analysis.total_size
        estimated_new_size = max(0, current_size - total_estimated_savings)
        savings_percent = (total_estimated_savings / current_size * 100) if current_size > 0 else 0

        return {
            "current_size": current_size,
            "estimated_savings": total_estimated_savings,
            "estimated_new_size": estimated_new_size,
            "savings_percent": savings_percent,
            "by_category": by_category,
        }